[project]
name = "trading-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastparquet>=2026.5.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pathlib>=1.0.1",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
